# Generated by Django 5.0.4 on 2024-04-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApxCountry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('country', models.CharField(max_length=40)),
                ('template', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ApxObsCodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('system', models.CharField(max_length=8)),
                ('observatory', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('instrument', models.CharField(max_length=60)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('subdiscipline', models.CharField(max_length=6)),
                ('telescope', models.CharField(max_length=40)),
                ('aperture', models.FloatField()),
                ('note', models.TextField()),
            ],
        ),
    ]
